import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { Header } from '@/shared/ui/header'
import { Footer } from '@/shared/ui/footer'
import { Provider } from './provider'
import './globals.css'

const montserrat = Montserrat({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
  display: 'swap'
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ru'>
      <body className={`${montserrat.className} bg-[var(--bg)] flex flex-col min-h-[100svh]`}>
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
